### ISSUE TITLE
angle issue

### ISSUE THREAD

**Issue by asmajavaidd** [Larkinnjm1/Masters-Thesis-GLCM-repository#1]
Hi I have a quick question for you. Since you already worked in GLCM and calculated glcm for 4 directions.
So I am trying to calculate the texture features of my 1 image using GLCM. Now if I use these properties properties = ['contrast', 'energy','ASM', 'homogeneity', 'correlation', 'dissimilarity'] and calculate GLCM in 4 direction angles like [0, np.pi / 4, np.pi / 2, 3 * np.pi / 4] then I get 4 *6=24 feature values. Now my professor is saying 24 features are not enough for the feature selection so calculate GLCM in more directions to get more feature values like previously my directions were [0, 45,90,135] now he is asking me to calculate in [120, 180, 270], etc just to get more features. But everywhere on google, I have seen people are calculating GLCM in the standard four directions that is [0, np.pi / 4, np.pi / 2, 3 * np.pi / 4] so is this correct if I calculate GLCM in the other directions which he mentioned?

**Comment by Larkinnjm1** [comment]
Hi Asmajavaidd,

Your professor could be correct in terms of increasing the number of features with additional angles however the first 4 outlined in this project are initially good enough to get good separation with whichever distance metric you are using to compare the different regions that you are using to compare the different features extracted from your image regions i.e. Bhattacharyya , EMD, Mahalanobis distance etc. If they are unsuccessful either in combination or in terms of using each set individually to get good distance between the regions then you can look to increase the number of angles or perhaps try some image preprocessing to perhaps increase the separation between the image regions in another manner.

**Comment by asmajavaidd** [comment]
@Larkinnjm1 thank you so much for your reply. Since you already work in calculating GLCM so I have just one more question from you. 
Actually, everywhere on google, I found researches or the helpers at stack are only using those standard 4 angles that is why I thought to ask that maybe you know about it because you work on it. Between @Larkinnjm1  I also see most of the researchers just calculate 6 properties of glcm like ['contrast', 'energy','ASM', 'homogeneity', 'correlation', 'dissimilarity'] . I am trying to find different properties like entropy, sum average, sum variance but I am getting the error. Is that because greycoprops does not calculate these properties in the below way?

print(skimage.feature.greycoprops(g, 'sum variance ')[0][0])
print(skimage.feature.greycoprops(g, 'entropy')[0][0])
print(skimage.feature.greycoprops(g, 'sum average,')[0][0])
print(skimage.feature.greycoprops(g, 'Cluster Shade')[0][0])

**Comment by Larkinnjm1** [comment]
Yes in the sense that skimage.feature.greycoprops does not actually have any way of calculating those automatically it only can calculate the 6 you have mentioned above automatically as per sklearn's documentation 

https://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.greycoprops

If you want to do any of the above items you have mentioned you will have to perform additional transformations to the matrices you have above. I did not use any of the features like "Cluster Shade" you have mentioned above from memory however I believe there is another python library 

https://pyradiomics.readthedocs.io/en/latest/features.html

which you could try to use which I believe has some of the properties you are looking for baked into it for GLCM analysis. Please note however I have not used this library myself so I don't have great knowledge around the ins and out of how to use it so you will have to do a bit of leg work to get the gist of how to implement it.

**Comment by asmajavaidd** [comment]
@Larkinnjm1 thank you so much for your reply. Since you already work in calculating GLCM so I have just one more question from you. 
Actually, everywhere on google, I found researches or the helpers at stack are only using those standard 4 angles that is why I thought to ask that maybe you know about it because you work on it. Between @Larkinnjm1  you just calculate 4 properties of glcm. I am trying to do exactly on your way but trying to find different properties like entropy, sum average, sum variance but I am getting the error. Is that because greycoprops does not calculate these properties?

print(skimage.feature.greycoprops(g, 'sum variance ')[0][0])
print(skimage.feature.greycoprops(g, 'entropy')[0][0])
print(skimage.feature.greycoprops(g, 'sum average,')[0][0])
print(skimage.feature.greycoprops(g, 'Cluster Shade')[0][0])

**Comment by asmajavaidd** [comment]
@Larkinnjm1 Thank You so much for your kind sugeestions. I really appreciate it.
